# cloudbuild.yml
steps:
    # Step to trigger GitHub Actions workflow
    - name: 'curlimages/curl:7.85.0'
      id: 'Trigger GitHub Actions Workflow'
      entrypoint: 'curl'
      args:
        - '-X'
        - 'POST'
        - '-H'
        - 'Accept: application/vnd.github+json'
        - '-H'
        - 'Authorization: Bearer ${_GITHUB_TOKEN}'
        - 'https://api.github.com/repos/Wolf1904/DefenderBytes/actions/workflows/build.yml/dispatches'
        - '-d'
        - |
          {
            "ref": "main"
          }
            
    substitutions:
        _GITHUB_TOKEN: 'GIT_TOKEN'
  